// Generated by hardware/scripts/gen_downloads.py -- do not edit by hand.
window.DOWNLOADS = [
  {
    "key": "tetrahedron",
    "name": "Tetrahedron",
    "faces": 4,
    "vertices": 4,
    "sides": 3,
    "strip": 2,
    "foldAngles": [
      109.47
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_tetrahedron.pdf",
      "edge": 94.7,
      "gap": 3.13
    },
    "stl": {
      "path": "hardware/tests/flat_strip_tetrahedron.stl",
      "edge": 22.0,
      "turn": 120.0
    },
    "extras": []
  },
  {
    "key": "cube",
    "name": "Cube",
    "faces": 6,
    "vertices": 8,
    "sides": 4,
    "strip": 3,
    "foldAngles": [
      90.0
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_cube.pdf",
      "edge": 52.4,
      "gap": 5.24
    },
    "stl": {
      "path": "hardware/tests/flat_strip_cube.stl",
      "edge": 22.0,
      "turn": 0.0
    },
    "extras": []
  },
  {
    "key": "octahedron",
    "name": "Octahedron",
    "faces": 8,
    "vertices": 6,
    "sides": 3,
    "strip": 4,
    "foldAngles": [
      70.53
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_octahedron.pdf",
      "edge": 71.3,
      "gap": 5.19
    },
    "stl": {
      "path": "hardware/tests/flat_strip_octahedron.stl",
      "edge": 22.0,
      "turn": 240.0
    },
    "extras": []
  },
  {
    "key": "trapezohedron",
    "name": "Pentagonal Trapezohedron",
    "faces": 10,
    "vertices": 12,
    "sides": 4,
    "strip": 5,
    "foldAngles": [
      59.45,
      73.3
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_trapezohedron.pdf",
      "edge": 65.8,
      "gap": 7.27
    },
    "stl": {
      "path": "hardware/tests/flat_strip_trapezohedron.stl",
      "edge": 22.0,
      "turn": 307.8855
    },
    "extras": []
  },
  {
    "key": "dodecahedron",
    "name": "Dodecahedron",
    "faces": 12,
    "vertices": 20,
    "sides": 5,
    "strip": 6,
    "foldAngles": [
      63.43
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_dodecahedron.pdf",
      "edge": 29.7,
      "gap": 4.22
    },
    "stl": {
      "path": "hardware/tests/flat_strip_dodecahedron.stl",
      "edge": 22.0,
      "turn": 108.0
    },
    "extras": []
  },
  {
    "key": "icosahedron",
    "name": "Icosahedron",
    "faces": 20,
    "vertices": 12,
    "sides": 3,
    "strip": 10,
    "foldAngles": [
      41.81
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_icosahedron.pdf",
      "edge": 44.7,
      "gap": 4.91
    },
    "stl": {
      "path": "hardware/tests/flat_strip_icosahedron.stl",
      "edge": 22.0,
      "turn": 300.0
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_icosahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  }
];
