// Generated by hardware/scripts/gen_downloads.py -- do not edit by hand.
window.DOWNLOADS = [
  {
    "key": "tetrahedron",
    "name": "Tetrahedron",
    "faces": 4,
    "vertices": 4,
    "sides": 3,
    "strip": 2,
    "foldAngles": [
      109.47
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_tetrahedron.pdf",
      "edge": 83.7,
      "gap": 3.42
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 27.4,
          "path": "hardware/tests/flat_strip_tetrahedron_25mm.stl",
          "bed": [
            41.0,
            36.0
          ],
          "turn": 120.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 35.08,
          "path": "hardware/tests/flat_strip_tetrahedron_32mm.stl",
          "bed": [
            52.0,
            46.0
          ],
          "turn": 120.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 43.85,
          "path": "hardware/tests/flat_strip_tetrahedron_40mm.stl",
          "bed": [
            65.0,
            56.0
          ],
          "turn": 300.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 54.81,
          "path": "hardware/tests/flat_strip_tetrahedron_50mm.stl",
          "bed": [
            82.0,
            91.0
          ],
          "turn": 120.0,
          "sockets": 4,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 69.06,
          "path": "hardware/tests/flat_strip_tetrahedron_63mm.stl",
          "bed": [
            103.0,
            87.0
          ],
          "turn": 120.0,
          "sockets": 4,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_tetrahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "cube",
    "name": "Cube",
    "faces": 6,
    "vertices": 8,
    "sides": 4,
    "strip": 3,
    "foldAngles": [
      90.0
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_cube.pdf",
      "edge": 50.9,
      "gap": 4.81
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 16.67,
          "path": "hardware/tests/flat_strip_cube_25mm.stl",
          "bed": [
            50.0,
            27.0
          ],
          "turn": 0.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 21.33,
          "path": "hardware/tests/flat_strip_cube_32mm.stl",
          "bed": [
            64.0,
            33.0
          ],
          "turn": 0.0,
          "sockets": 4,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 26.67,
          "path": "hardware/tests/flat_strip_cube_40mm.stl",
          "bed": [
            80.0,
            41.0
          ],
          "turn": 0.0,
          "sockets": 4,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 33.33,
          "path": "hardware/tests/flat_strip_cube_50mm.stl",
          "bed": [
            100.0,
            50.0
          ],
          "turn": 0.0,
          "sockets": 4,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 42.0,
          "path": "hardware/tests/flat_strip_cube_63mm.stl",
          "bed": [
            126.0,
            62.0
          ],
          "turn": 0.0,
          "sockets": 4,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_cube.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "octahedron",
    "name": "Octahedron",
    "faces": 8,
    "vertices": 6,
    "sides": 3,
    "strip": 4,
    "foldAngles": [
      70.53
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_octahedron.pdf",
      "edge": 65.0,
      "gap": 4.97
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 21.27,
          "path": "hardware/tests/flat_strip_octahedron_25mm.stl",
          "bed": [
            42.0,
            47.0
          ],
          "turn": 240.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 27.22,
          "path": "hardware/tests/flat_strip_octahedron_32mm.stl",
          "bed": [
            54.0,
            60.0
          ],
          "turn": 240.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 34.03,
          "path": "hardware/tests/flat_strip_octahedron_40mm.stl",
          "bed": [
            68.0,
            74.0
          ],
          "turn": 60.0,
          "sockets": 2,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 42.54,
          "path": "hardware/tests/flat_strip_octahedron_50mm.stl",
          "bed": [
            85.0,
            92.0
          ],
          "turn": 60.0,
          "sockets": 2,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 53.6,
          "path": "hardware/tests/flat_strip_octahedron_63mm.stl",
          "bed": [
            107.0,
            115.0
          ],
          "turn": 240.0,
          "sockets": 2,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_octahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "trapezohedron",
    "name": "Pentagonal Trapezohedron",
    "faces": 10,
    "vertices": 12,
    "sides": 4,
    "strip": 5,
    "foldAngles": [
      51.83,
      90.0
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_trapezohedron.pdf",
      "edge": 57.6,
      "gap": 4.41
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 18.84,
          "path": "hardware/tests/flat_strip_trapezohedron_25mm.stl",
          "bed": [
            56.0,
            47.0
          ],
          "turn": 335.4819,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 24.11,
          "path": "hardware/tests/flat_strip_trapezohedron_32mm.stl",
          "bed": [
            72.0,
            60.0
          ],
          "turn": 335.4819,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 30.14,
          "path": "hardware/tests/flat_strip_trapezohedron_40mm.stl",
          "bed": [
            90.0,
            74.0
          ],
          "turn": 335.4819,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 37.67,
          "path": "hardware/tests/flat_strip_trapezohedron_50mm.stl",
          "bed": [
            113.0,
            91.0
          ],
          "turn": 335.4819,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 47.47,
          "path": "hardware/tests/flat_strip_trapezohedron_63mm.stl",
          "bed": [
            142.0,
            114.0
          ],
          "turn": 335.4819,
          "sockets": 0,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_trapezohedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "dodecahedron",
    "name": "Dodecahedron",
    "faces": 12,
    "vertices": 20,
    "sides": 5,
    "strip": 6,
    "foldAngles": [
      63.43
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_dodecahedron.pdf",
      "edge": 28.9,
      "gap": 4.56
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 9.46,
          "path": "hardware/tests/flat_strip_dodecahedron_25mm.stl",
          "bed": [
            68.0,
            47.0
          ],
          "turn": 108.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 12.11,
          "path": "hardware/tests/flat_strip_dodecahedron_32mm.stl",
          "bed": [
            87.0,
            60.0
          ],
          "turn": 108.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 15.13,
          "path": "hardware/tests/flat_strip_dodecahedron_40mm.stl",
          "bed": [
            108.0,
            74.0
          ],
          "turn": 288.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 18.92,
          "path": "hardware/tests/flat_strip_dodecahedron_50mm.stl",
          "bed": [
            135.0,
            91.0
          ],
          "turn": 108.0,
          "sockets": 4,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 23.84,
          "path": "hardware/tests/flat_strip_dodecahedron_63mm.stl",
          "bed": [
            171.0,
            114.0
          ],
          "turn": 288.0,
          "sockets": 4,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_dodecahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "icosahedron",
    "name": "Icosahedron",
    "faces": 20,
    "vertices": 12,
    "sides": 3,
    "strip": 10,
    "foldAngles": [
      41.81
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_icosahedron.pdf",
      "edge": 43.9,
      "gap": 6.42
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 14.35,
          "path": "hardware/tests/flat_strip_icosahedron_25mm.stl",
          "bed": [
            57.0,
            58.0
          ],
          "turn": 300.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 32.0,
          "edge": 18.37,
          "path": "hardware/tests/flat_strip_icosahedron_32mm.stl",
          "bed": [
            73.0,
            73.0
          ],
          "turn": 120.0,
          "sockets": 0,
          "inlays": 2
        },
        {
          "mm": 40.0,
          "edge": 22.96,
          "path": "hardware/tests/flat_strip_icosahedron_40mm.stl",
          "bed": [
            92.0,
            91.0
          ],
          "turn": 120.0,
          "sockets": 6,
          "inlays": 2
        },
        {
          "mm": 50.0,
          "edge": 28.7,
          "path": "hardware/tests/flat_strip_icosahedron_50mm.stl",
          "bed": [
            115.0,
            113.0
          ],
          "turn": 120.0,
          "sockets": 6,
          "inlays": 2
        },
        {
          "mm": 63.0,
          "edge": 36.16,
          "path": "hardware/tests/flat_strip_icosahedron_63mm.stl",
          "bed": [
            144.0,
            141.0
          ],
          "turn": 300.0,
          "sockets": 6,
          "inlays": 2
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_icosahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  }
];
