// Generated by hardware/scripts/gen_downloads.py -- do not edit by hand.
window.DOWNLOADS = [
  {
    "key": "tetrahedron",
    "name": "Tetrahedron",
    "faces": 4,
    "vertices": 4,
    "sides": 3,
    "strip": 2,
    "foldAngles": [
      109.47
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_tetrahedron.pdf",
      "edge": 83.7,
      "gap": 3.42
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 27.4,
          "path": "hardware/tests/flat_strip_tetrahedron_25mm.stl",
          "bed": [
            40.8,
            23.6
          ],
          "turn": 300.0
        },
        {
          "mm": 32.0,
          "edge": 35.08,
          "path": "hardware/tests/flat_strip_tetrahedron_32mm.stl",
          "bed": [
            52.3,
            30.2
          ],
          "turn": 120.0
        },
        {
          "mm": 40.0,
          "edge": 43.85,
          "path": "hardware/tests/flat_strip_tetrahedron_40mm.stl",
          "bed": [
            65.5,
            37.8
          ],
          "turn": 120.0
        },
        {
          "mm": 50.0,
          "edge": 54.81,
          "path": "hardware/tests/flat_strip_tetrahedron_50mm.stl",
          "bed": [
            81.9,
            47.3
          ],
          "turn": 300.0
        },
        {
          "mm": 63.0,
          "edge": 69.06,
          "path": "hardware/tests/flat_strip_tetrahedron_63mm.stl",
          "bed": [
            103.3,
            59.6
          ],
          "turn": 120.0
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_tetrahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "cube",
    "name": "Cube",
    "faces": 6,
    "vertices": 8,
    "sides": 4,
    "strip": 3,
    "foldAngles": [
      90.0
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_cube.pdf",
      "edge": 50.9,
      "gap": 4.81
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 16.67,
          "path": "hardware/tests/flat_strip_cube_25mm.stl",
          "bed": [
            49.8,
            16.5
          ],
          "turn": 180.0
        },
        {
          "mm": 32.0,
          "edge": 21.33,
          "path": "hardware/tests/flat_strip_cube_32mm.stl",
          "bed": [
            63.8,
            21.2
          ],
          "turn": 180.0
        },
        {
          "mm": 40.0,
          "edge": 26.67,
          "path": "hardware/tests/flat_strip_cube_40mm.stl",
          "bed": [
            79.8,
            26.5
          ],
          "turn": 180.0
        },
        {
          "mm": 50.0,
          "edge": 33.33,
          "path": "hardware/tests/flat_strip_cube_50mm.stl",
          "bed": [
            99.8,
            33.2
          ],
          "turn": 0.0
        },
        {
          "mm": 63.0,
          "edge": 42.0,
          "path": "hardware/tests/flat_strip_cube_63mm.stl",
          "bed": [
            125.8,
            41.8
          ],
          "turn": 0.0
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_cube.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "octahedron",
    "name": "Octahedron",
    "faces": 8,
    "vertices": 6,
    "sides": 3,
    "strip": 4,
    "foldAngles": [
      70.53
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_octahedron.pdf",
      "edge": 65.0,
      "gap": 4.97
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 21.27,
          "path": "hardware/tests/flat_strip_octahedron_25mm.stl",
          "bed": [
            42.3,
            36.7
          ],
          "turn": 60.0
        },
        {
          "mm": 32.0,
          "edge": 27.22,
          "path": "hardware/tests/flat_strip_octahedron_32mm.stl",
          "bed": [
            54.2,
            47.0
          ],
          "turn": 60.0
        },
        {
          "mm": 40.0,
          "edge": 34.03,
          "path": "hardware/tests/flat_strip_octahedron_40mm.stl",
          "bed": [
            67.8,
            58.8
          ],
          "turn": 240.0
        },
        {
          "mm": 50.0,
          "edge": 42.54,
          "path": "hardware/tests/flat_strip_octahedron_50mm.stl",
          "bed": [
            84.8,
            73.5
          ],
          "turn": 240.0
        },
        {
          "mm": 63.0,
          "edge": 53.6,
          "path": "hardware/tests/flat_strip_octahedron_63mm.stl",
          "bed": [
            106.9,
            92.7
          ],
          "turn": 60.0
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_octahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "trapezohedron",
    "name": "Pentagonal Trapezohedron",
    "faces": 10,
    "vertices": 12,
    "sides": 4,
    "strip": 5,
    "foldAngles": [
      51.83,
      90.0
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_trapezohedron.pdf",
      "edge": 57.6,
      "gap": 4.41
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 18.84,
          "path": "hardware/tests/flat_strip_trapezohedron_25mm.stl",
          "bed": [
            56.2,
            37.2
          ],
          "turn": 335.4819
        },
        {
          "mm": 32.0,
          "edge": 24.11,
          "path": "hardware/tests/flat_strip_trapezohedron_32mm.stl",
          "bed": [
            72.1,
            47.7
          ],
          "turn": 335.4819
        },
        {
          "mm": 40.0,
          "edge": 30.14,
          "path": "hardware/tests/flat_strip_trapezohedron_40mm.stl",
          "bed": [
            90.2,
            59.7
          ],
          "turn": 335.4819
        },
        {
          "mm": 50.0,
          "edge": 37.67,
          "path": "hardware/tests/flat_strip_trapezohedron_50mm.stl",
          "bed": [
            112.8,
            74.7
          ],
          "turn": 335.4819
        },
        {
          "mm": 63.0,
          "edge": 47.47,
          "path": "hardware/tests/flat_strip_trapezohedron_63mm.stl",
          "bed": [
            142.1,
            94.1
          ],
          "turn": 335.4819
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_trapezohedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "dodecahedron",
    "name": "Dodecahedron",
    "faces": 12,
    "vertices": 20,
    "sides": 5,
    "strip": 6,
    "foldAngles": [
      63.43
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_dodecahedron.pdf",
      "edge": 28.9,
      "gap": 4.56
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 9.46,
          "path": "hardware/tests/flat_strip_dodecahedron_25mm.stl",
          "bed": [
            67.6,
            37.9
          ],
          "turn": 288.0
        },
        {
          "mm": 32.0,
          "edge": 12.11,
          "path": "hardware/tests/flat_strip_dodecahedron_32mm.stl",
          "bed": [
            86.5,
            48.6
          ],
          "turn": 108.0
        },
        {
          "mm": 40.0,
          "edge": 15.13,
          "path": "hardware/tests/flat_strip_dodecahedron_40mm.stl",
          "bed": [
            108.2,
            60.8
          ],
          "turn": 288.0
        },
        {
          "mm": 50.0,
          "edge": 18.92,
          "path": "hardware/tests/flat_strip_dodecahedron_50mm.stl",
          "bed": [
            135.3,
            76.1
          ],
          "turn": 288.0
        },
        {
          "mm": 63.0,
          "edge": 23.84,
          "path": "hardware/tests/flat_strip_dodecahedron_63mm.stl",
          "bed": [
            170.5,
            95.9
          ],
          "turn": 108.0
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_dodecahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  },
  {
    "key": "icosahedron",
    "name": "Icosahedron",
    "faces": 20,
    "vertices": 12,
    "sides": 3,
    "strip": 10,
    "foldAngles": [
      41.81
    ],
    "net": {
      "path": "hardware/tests/flat_strip_template_icosahedron.pdf",
      "edge": 43.9,
      "gap": 6.42
    },
    "stl": {
      "default": 40.0,
      "sizes": [
        {
          "mm": 25.0,
          "edge": 14.35,
          "path": "hardware/tests/flat_strip_icosahedron_25mm.stl",
          "bed": [
            57.1,
            49.6
          ],
          "turn": 300.0
        },
        {
          "mm": 32.0,
          "edge": 18.37,
          "path": "hardware/tests/flat_strip_icosahedron_32mm.stl",
          "bed": [
            73.2,
            63.5
          ],
          "turn": 120.0
        },
        {
          "mm": 40.0,
          "edge": 22.96,
          "path": "hardware/tests/flat_strip_icosahedron_40mm.stl",
          "bed": [
            91.6,
            79.4
          ],
          "turn": 120.0
        },
        {
          "mm": 50.0,
          "edge": 28.7,
          "path": "hardware/tests/flat_strip_icosahedron_50mm.stl",
          "bed": [
            114.5,
            99.3
          ],
          "turn": 120.0
        },
        {
          "mm": 63.0,
          "edge": 36.16,
          "path": "hardware/tests/flat_strip_icosahedron_63mm.stl",
          "bed": [
            144.4,
            125.1
          ],
          "turn": 120.0
        }
      ]
    },
    "extras": [
      {
        "label": "Schlegel diagram",
        "path": "hardware/tests/schlegel_icosahedron.pdf",
        "note": "the whole edge graph flat on one page, for tracing cycles by pencil"
      }
    ]
  }
];
