"""Writes schlegel.js: the flat layout of every solid's Schlegel diagram, for
the web page to morph the 3D solid into.

    python3 hardware/scripts/gen_schlegel_js.py

The layout is not recomputed in JavaScript. It comes from the same picker
gen_schlegel_pdf.py uses -- sweep the projections, build Tutte's embedding,
respace the rings, score them all by the tightest region each one draws, and
keep the best -- so the diagram the page flattens into is the diagram printed
on the worksheet, down to the vertex. Porting that sweep to the browser would
be a second implementation to keep in step, and the first thing it would do
is drift.

Requires: pip install matplotlib numpy

Run from the repo root.
"""

import json

import numpy as np

from polyhedra import SOLIDS
import gen_schlegel_pdf as S


def layout(solid):
    edges = S.all_edges(solid.faces)
    options = S.candidates(solid, edges)
    assert options, f"no construction produced a valid diagram for {solid.name}"
    label = max(options, key=lambda k: S.score(options[k], solid, edges))
    pts = S.upright(options[label], solid.faces[S.VIEW_FACE][0])
    S.verify(pts, solid.faces, edges, S.VIEW_FACE)
    # centred on the origin and normalised to unit width, so the page can
    # scale it to whatever the solid is drawn at
    pts = pts - (pts.max(0) + pts.min(0)) / 2
    pts = pts / max(np.ptp(pts[:, 0]), np.ptp(pts[:, 1]))
    return label, pts


if __name__ == "__main__":
    out = {}
    for key, solid in SOLIDS.items():
        label, pts = layout(solid)
        out[key] = {
            "viewFace": S.VIEW_FACE,
            "pts": [[round(float(x), 6), round(float(y), 6)] for x, y in pts],
        }
        print(f"{solid.name:26s} {label}")

    with open("schlegel.js", "w") as f:
        f.write("// Generated by hardware/scripts/gen_schlegel_js.py -- "
                "do not edit by hand.\n")
        f.write("// The same layout gen_schlegel_pdf.py prints on the "
                "worksheet, so the page\n// and the paper agree.\n")
        f.write("window.SCHLEGEL = " + json.dumps(out, indent=2) + ";\n")
    print(f"\nwrote schlegel.js ({len(out)} solids)")
