"""Write polyhedra.js, the visualizer's copy of the solids.

The page used to carry its own table of vertices, faces and cycles. It had
drifted: the dodecahedron's cycle was an entirely different cut from the one
the STL folds along, and the tetrahedron's index list matched while its
vertices did not -- so the same cycle [0,1,2,3] named a different cut, which
is the kind of disagreement that reports nothing and looks like nothing.

polyhedra.py is canonical because it checks itself: Euler's formula, that the
cycle visits every vertex exactly once, that every step of it is a real edge,
and that every face is planar. The page now reads what those checks passed.

A generated .js rather than .json so the page still opens from a file:// URL
with no server, the same way downloads.js already works.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import census
import polyhedra as P

ORDER = ["tetrahedron", "cube", "octahedron", "trapezohedron",
         "dodecahedron", "icosahedron"]

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "polyhedra.js")


def num(x):
    """Enough digits that the page's geometry is the same geometry."""
    v = float(x)
    if v == int(v):
        return str(int(v))
    return repr(round(v, 12))


def census_js(c):
    """How many ways this solid can be cut, counted by census.py."""
    return ("{" + ", ".join(
        f"{k}: {str(v).lower() if isinstance(v, bool) else v}"
        for k, v in c.items()) + "}")


def main():
    assert set(ORDER) == set(P.SOLIDS), "gen_polyhedra_js: ORDER is out of date"
    lines = [
        "// GENERATED by hardware/scripts/gen_polyhedra_js.py -- do not edit.",
        "//",
        "// The solids, straight from hardware/scripts/polyhedra.py, which",
        "// verifies each one: Euler's formula, the cycle visiting every vertex",
        "// exactly once, every step of it being a real edge, and every face",
        "// being planar. The page and the printed files therefore describe the",
        "// same cut -- they did not always, and nothing said so.",
        "//",
        "// Each one also carries its census: how many Hamiltonian cycles it",
        "// has, how many of those are essentially different, how many fold",
        "// into two strips, and whether the cut shipped here has congruent",
        "// halves. See hardware/scripts/census.py.",
        "window.POLYHEDRA_DATA = {",
    ]
    for key in ORDER:
        s = P.SOLIDS[key]
        verts = ", ".join("[" + ", ".join(num(c) for c in v) + "]"
                          for v in s.vertices)
        faces = ", ".join("[" + ",".join(str(i) for i in f) + "]"
                          for f in s.faces)
        lines += [
            f'  {key}: {{',
            f'    label: {s.label!r},'.replace("'", '"'),
            f'    vertices: [{verts}],',
            f'    faces: [{faces}],',
            f'    cycle: [{",".join(str(i) for i in s.cycle)}],',
            f'    census: {census_js(census.census(s))}',
            '  },',
        ]
    lines.append("};")
    io.open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}  "
          f"({len(ORDER)} solids, {os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
