"""Builds the fold-up net PDF and the 3D-print STL for every solid, then
writes downloads.js -- the manifest the web page reads to offer them.

The manifest is generated rather than typed so it cannot drift from the
files: the sizes quoted on the page are scraped from the generators' own
output on the run that produced those very files. It is a plain script
assigning a global rather than JSON fetched at runtime, so the page works
when opened straight off disk as well as over HTTP.

Run from the repo root:
    python3 hardware/scripts/gen_downloads.py
"""

import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from polyhedra import SOLIDS   # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = "hardware/tests"
EXTRAS = {"icosahedron": [("Schlegel diagram", f"{OUT_DIR}/schlegel_icosahedron.pdf",
                          "the whole edge graph flat on one page, for tracing cycles by pencil")]}


def run(script, key):
    r = subprocess.run([sys.executable, os.path.join(HERE, script), key],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"{script} {key} failed:\n{r.stdout}\n{r.stderr}")
    return r.stdout


def grab(text, pattern, cast=float):
    m = re.search(pattern, text)
    return cast(m.group(1)) if m else None


if __name__ == "__main__":
    entries = []
    for key, solid in SOLIDS.items():
        pdf_log = run("gen_flat_strip_pdf.py", key)
        stl_log = run("gen_flat_strip.py", key)

        caps = solid.strips()
        entry = {
            "key": key,
            "name": solid.name,
            "faces": len(solid.faces),
            "vertices": len(solid.vertices),
            "sides": len(solid.faces[caps[0][0]]),
            "strip": len(caps[0]),
            "foldAngles": sorted({round(v, 2) for v in solid.fold_angles().values()}),
            "net": {
                "path": f"{OUT_DIR}/flat_strip_template_{key}.pdf",
                "edge": grab(pdf_log, r"using edge length ([\d.]+)mm"),
                "gap": grab(pdf_log, r"nest with ([\d.]+)mm"),
            },
            "stl": {
                "path": f"{OUT_DIR}/flat_strip_{solid.name.split()[-1].lower()}.stl",
                "edge": grab(stl_log, r"edge ([\d.]+)mm", float) or 22.0,
                "turn": grab(stl_log, r"a ([\d.]+) deg turn"),
            },
            "extras": [{"label": l, "path": p, "note": n}
                       for l, p, n in EXTRAS.get(key, [])],
        }
        for f in [entry["net"]["path"], entry["stl"]["path"]] + [e["path"] for e in entry["extras"]]:
            assert os.path.exists(f), f"{f} was not produced"
        entries.append(entry)
        print(f"{solid.name:26s} net {entry['net']['edge']:5.1f}mm edges, "
              f"stl {entry['stl']['path'].split('/')[-1]}")

    with open("downloads.js", "w") as f:
        f.write("// Generated by hardware/scripts/gen_downloads.py -- do not edit by hand.\n")
        f.write("window.DOWNLOADS = " + json.dumps(entries, indent=2) + ";\n")
    print(f"\nwrote downloads.js ({len(entries)} solids)")
