"""Builds the fold-up net PDF, the Schlegel diagram and the 3D-print STLs for
every solid, then writes downloads.js -- the manifest the web page reads to
offer them.

The STL comes in several sizes, one file each. That is not laziness about a
slider: the hinge is absolute millimetres, so a strip cannot be rescaled
after it is generated without rescaling the hinge and ruining the fold.
Every size on offer is therefore built here and checked at its own size.

The manifest is generated rather than typed so it cannot drift from the
files: the sizes quoted on the page are scraped from the generators' own
output on the run that produced those very files. It is a plain script
assigning a global rather than JSON fetched at runtime, so the page works
when opened straight off disk as well as over HTTP.

Run from the repo root:
    python3 hardware/scripts/gen_downloads.py
"""

import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from polyhedra import SOLIDS   # noqa: E402
# The size ladder lives with the generator that has to honour it, so the page
# can never offer a rung nobody built. Importing it only reads the module's
# constants -- the build runs under its __main__.
from gen_flat_strip import SIZES_MM, DEFAULT_SIZE_MM   # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = "hardware/tests"
SCHLEGEL_NOTE = "the whole edge graph flat on one page, for tracing cycles by pencil"


def run(script, *args):
    r = subprocess.run([sys.executable, os.path.join(HERE, script), *args],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"{script} {' '.join(args)} failed:\n{r.stdout}\n{r.stderr}")
    return r.stdout


def grab(text, pattern, cast=float):
    m = re.search(pattern, text)
    return cast(m.group(1)) if m else None


if __name__ == "__main__":
    entries = []
    for key, solid in SOLIDS.items():
        pdf_log = run("gen_flat_strip_pdf.py", key)
        run("gen_schlegel_pdf.py", key)

        # One print per rung of the ladder. The part cannot be scaled after
        # the fact -- the hinge is absolute millimetres -- so every size the
        # page offers is generated here and passes the generator's own checks
        # at that size, footprint included.
        rungs = []
        for size in SIZES_MM:
            log = run("gen_flat_strip.py", key, str(size))
            fp = re.search(r"cap0: .*footprint ([\d.]+) x ([\d.]+)", log)
            rungs.append({
                "mm": size,
                "edge": grab(log, r"wants edge ([\d.]+)mm"),
                "path": re.search(r"wrote (\S+\.stl)", log).group(1),
                "bed": [float(fp.group(1)), float(fp.group(2))],
                "turn": grab(log, r"a ([\d.]+) deg turn"),
            })

        caps = solid.strips()
        entry = {
            "key": key,
            "name": solid.name,
            "faces": len(solid.faces),
            "vertices": len(solid.vertices),
            "sides": len(solid.faces[caps[0][0]]),
            "strip": len(caps[0]),
            "foldAngles": sorted({round(v, 2) for v in solid.fold_angles().values()}),
            "net": {
                "path": f"{OUT_DIR}/flat_strip_template_{key}.pdf",
                "edge": grab(pdf_log, r"using edge length ([\d.]+)mm"),
                "gap": grab(pdf_log, r"nest with ([\d.]+)mm"),
            },
            "stl": {
                "default": DEFAULT_SIZE_MM,
                "sizes": rungs,
            },
            "extras": [{"label": "Schlegel diagram",
                        "path": f"{OUT_DIR}/schlegel_{key}.pdf",
                        "note": SCHLEGEL_NOTE}],
        }
        for f in ([entry["net"]["path"]] + [r["path"] for r in rungs]
                  + [e["path"] for e in entry["extras"]]):
            assert os.path.exists(f), f"{f} was not produced"
        entries.append(entry)
        print(f"{solid.name:26s} net {entry['net']['edge']:5.1f}mm edges, "
              f"stl at " + ", ".join(f"{r['mm']:g}mm ({r['edge']:.1f}mm edges, "
                                     f"{r['bed'][0]:.0f}x{r['bed'][1]:.0f} bed)"
                                     for r in rungs))

    with open("downloads.js", "w") as f:
        f.write("// Generated by hardware/scripts/gen_downloads.py -- do not edit by hand.\n")
        f.write("window.DOWNLOADS = " + json.dumps(entries, indent=2) + ";\n")
    print(f"\nwrote downloads.js ({len(entries)} solids)")
